logging:
  level:
    org:
      springframework:
        orm:
          jpa: INFO
          jpa.JpaTransactionManager: DEBUG
        transaction: INFO
        transaction.interceptor: TRACE
spring:
  application.name: later
  main.banner-mode: OFF
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  datasource:
    username: "dbuser"
    password: "12345"
    url: "jdbc:postgresql://localhost:6432/later"
    driver-class-name: "org.postgresql.Driver"